# Generated by Django 4.2.2 on 2023-06-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(default=1201813353, max_length=15),
            preserve_default=False,
        ),
    ]
